export const UPDATE_CONTAINER = 'UPDATE_CONTAINER';

export const UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE';

export const UPDATE_TAB = 'UPDATE_TAB';

export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';

export const TAB_INDEX_TAGS = 0;
export const TAB_INDEX_TRIGGERS = 1;
export const TAB_INDEX_VARIABLES = 2;
